[package]
name = "wiki_meilisearch"
version = "0.1.0"
edition = "2024"

description = "A Meilisearch integration module for Wiki.js."
repository = "https://github.com/mbround18/wikijs-module-meilisearch"
license = "./LICENSE"

[lib]
crate-type = ["cdylib"]
name = "meilisearch"
path = "src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.102"
meilisearch-sdk = { version = "0.29.1", features = ["futures-unsend"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
wasm-bindgen-futures = "0.4.52"
serde-wasm-bindgen = "0.6.5"
reqwest = { version = "0.12.23", features = ["json"] }
futures = "0.3.31"
futures-io = "0.3.31"
tokio = { version = "1.47.1", features = ["rt", "time", "macros"] }
thiserror = "2.0.16"
async-trait = "0.1.89"
log = "0.4.28"
env_logger = "0.11.8"
glob = "0.3.3"
regex = "1.11.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.52"

[target.wasm32-unknown-unknown.dependencies]
web-sys = { version = "0.3.79", features = ["Window", "Request", "Response", "RequestInit", "RequestMode"] }

[profile.release]
opt-level = "z"  # Optimize for speed, with some considerations for code size
lto = "fat"  # Link Time Optimization for smaller binaries
codegen-units = 1  # Single codegen unit to increase optimizations
panic = "abort"  # Use abort on panic to reduce binary size
