services:
  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: sqlite
    volumes:
      - ./pkg:/wiki/server/modules/search/meilisearch
      - ./tmp/wikijs:/wiki/data:rw
      - ./config/wiki.yml:/wiki/config.yml:r
    depends_on:
      - meilisearch
    links:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "demo"
      MEILI_NO_ANALYTICS: "true"
      MEILI_LOG_LEVEL: "DEBUG"
    volumes:
      - ./tmp/meilisearch:/meili_data
