name: Build and Release WASM

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Setup System
        run: |
          sudo apt-get update && sudo apt-get install -y cmake pkg-config libssl-dev zip
          make build

      - name: Create ZIP file
        run: |
          zip -r millisearch.zip pkg/*

      - name: Check for VERSION changes
        id: check_version
        run: |
          git fetch --prune --unshallow
          git diff --name-only HEAD^ HEAD | grep VERSION || echo "no changes"

      - name: Create Release Tag and Upload
        if: steps.check_version.outputs.result != 'no changes'
        id: create_release
        run: |
          VERSION=$(cat VERSION)
          TAG="v$VERSION"
          echo "Creating Release $TAG"
          gh release create $TAG millisearch.zip --title "$TAG" --notes "Release notes for version $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}